services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - appnet
    restart: unless-stopped

  wallet:
    build: ./gw-currency-wallet
    container_name: wallet
    depends_on:
      - exchanger
      - postgres
      - kafka
      
    env_file:
      - .env
    ports:
      - "8082:8082"
    volumes:
      - ./gw-currency-wallet:/app
    networks:
      - appnet

  exchanger:
    build: ./gw-exchanger 
    container_name: exchanger
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "50051:50051" 
    networks:
      - appnet
    restart: unless-stopped

  notification:
    build: ./gw-notification
    container_name: notification
    depends_on:
      - mongo-express
      - postgres
      - kafka
      - mongodb

    env_file:
      - .env
    networks:
      - appnet 
  analytics:
    build: ./gw-analytics
    container_name: analytics
    depends_on:
      - kafka
      - clickhouse
    env_file:
      - .env
    networks:
      - appnet
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - appnet
    restart: unless-stopped

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 

    networks:
    
      - appnet
    restart: unless-stopped

  mongo-express:
      image: mongo-express:latest
      container_name: mongo-express
      depends_on:
        - mongodb
      env_file:
        - .env
      ports:
        - "8084:8081"     
      networks:
        - appnet
      restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file:
      - .env
    ports:
      - "8123:8123"        
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - appnet
    restart: unless-stopped

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: clickhouse-ui
    hostname: ch-ui
    depends_on:
      - clickhouse
    ports:
      - "8085:3488"
    env_file:
      - .env
    networks:
      - appnet
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - appnet

    restart: unless-stopped
    
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8083:8080"
    networks:
      - appnet
    restart: unless-stopped


volumes:
  pgdata:
  kafka_data:
  clickhouse_data:
  mongodb_data:

networks:
  appnet:
    driver: bridge